config/routes.rb
Rails.application.routes.draw do
  get "dashboard/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  get "user", to: "users#new"
  root "home#index"
  # config/routes.rb

  # User Routes
  post "register", to: "users#create"
  put "users/:id/role", to: "users#update_role"

  get "/login", to: "sessions#new", as: :login
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy", as: :logout
  get "/dashboard", to: "dashboard#index", as: :dashboard

  resources :users, only: [:new, :create]


  # Spaces Routes
  resources :spaces, only: [:index, :new, :edit, :create, :update, :show, :destroy] do
    resources :objects, only: [:index, :create]
    resources :spots, only: [:index, :create]
    resources :bookings, only: [:new, :create]
  end







  # Objects Routes
  post "objects/delete", to: "objects#bulk_delete"

  # Spots Routes
  post "spots/delete", to: "spots#bulk_delete"

  # Bookings Routes
  resources :bookings, only: [:new, :index, :create, :destroy]

  # Spots_Booking Routes (if needed for specific spot booking management)
  resources :spots_booking, only: [:create]

end

app/views/layouts/_header.html.erb
<header class="fixed top-0 w-full bg-gray-900 text-white py-4 px-4 z-50">
  <nav class="max-w-7xl mx-auto flex justify-between items-center">
    <%= link_to "BUTT", root_path, class: "text-3xl font-bold text-brand-green hover:text-white" %>
    <div class="flex gap-8">
      <% if logged_in? %>
        <p>Hello, <%= current_user.name %>!</p>
        <%#= link_to "View Spaces", spaces_path, class: "text-white hover:text-brand-green transition-colors" %>
        <%#= link_to "Your Bookings", bookings_path, class: "text-white hover:text-brand-green transition-colors" %>
        <%= link_to "Профиль", dashboard_path, class: "text-white hover:text-brand-green transition-colors" %>
        <%= link_to "Выйти", logout_path, method: :get, class: "text-white hover:text-brand-green transition-colors" %>
      <% else %>
        <%= link_to "Регистрация", new_user_path, class: "text-white hover:text-brand-green transition-colors" %>
        <%= link_to "Войти", login_path, class: "text-white hover:text-brand-green transition-colors" %>
      <% end %>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "BUTT" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>


    <%= favicon_link_tag 'favicon3.svg', rel: 'icon', type: 'image/svg' %>
<!--    <link rel="icon" href="/icon.png" type="image/png">-->
<!--    <link rel="icon" href="/icon.svg" type="image/svg+xml">-->
<!--    <link rel="apple-touch-icon" href="/icon.png">-->

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%#<%= stylesheet_link_tag "application.tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%#<%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <%#<%= stylesheet_link_tag "application.tailwind", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
  <%= render 'layouts/header' %>
<!--  container mx-auto mt-28 px-5 flex-->
  <main class="">
      <%= yield %>
    </main>
  </body>
</html>